// # Entry point: Handles CLI commands (init / run-hook)
//
// Built with the Commander CLI framework. Two commands:
//   * `gitagent init`      — installs the pre-commit hook into this repo
//   * `gitagent run-hook`  — invoked BY the pre-commit hook on every commit:
//                            extracts the staged diff and (Milestone 1) writes
//                            a mock context file to prove the background loop works.

import { Command } from 'commander';
import { writeFileSync, mkdirSync, chmodSync, existsSync } from 'fs';
import { join } from 'path';
import { GitClient } from './git/gitClient.js';

const program = new Command();

program
  .name('gitagent')
  .description('GitAgent — auto-generate AI context files from your git commits')
  .version('1.0.0');

/**
 * run-hook: the command the pre-commit hook calls on every `git commit`.
 * Milestone 1 scope: prove the loop by extracting the staged diff via the
 * Interceptor (GitClient) and writing a hardcoded mock AGENTS.md, then
 * re-staging it so it lands in the same atomic commit.
 *
 * Outputs the DiffSummary as JSON to stdout for downstream parsers to consume.
 */
program
  .command('run-hook')
  .description('Invoked by the pre-commit hook: extract staged diff and generate context')
  .action(async () => {
    const git = new GitClient();

    // Abort gracefully if we somehow run outside a git repo (never block a commit).
    if (!(await git.validateGitEnvironment())) {
      console.error('[gitagent] Not a git repository — skipping.');
      process.stdout.write(JSON.stringify({ error: 'Not a git repository' }, null, 2));
      return;
    }

    console.log('[gitagent] ✓ pre-commit hook triggered');

    const summary = await git.getDiffSummary();
    console.log(`[gitagent] ${summary.totalChanges} staged file(s) detected:`);
    for (const f of summary.files) {
      console.log(`           ${f.status}  ${f.file}`);
    }

    if (summary.totalChanges === 0) {
      console.log('[gitagent] No staged changes — nothing to generate.');
      process.stdout.write(JSON.stringify(summary, null, 2));
      return;
    }

    // --- Milestone 1: write a hardcoded mock .md to prove the loop works ---
    const root = await git.getRepoRoot();
    const mockPath = join(root, 'AGENTS.md');
    const content =
      `# AGENTS.md\n\n` +
      `<!-- Generated by GitAgent's pre-commit hook. This proves the loop works. -->\n\n` +
      `## Files changed in the latest commit\n\n` +
      summary.files.map((f) => `- \`${f.file}\` (${f.status})`).join('\n') +
      `\n`;

    writeFileSync(mockPath, content, 'utf-8');
    console.log(`[gitagent] Wrote mock context → ${mockPath}`);

    // Git Index Restorer: stage the generated file into this commit.
    await git.stageFile(mockPath);
    console.log('[gitagent] ✓ Re-staged generated AGENTS.md into the commit');

    // Output the DiffSummary as JSON for downstream parsers to consume.
    process.stdout.write('\n');
    process.stdout.write(JSON.stringify(summary, null, 2));
  });

/**
 * init: installs the pre-commit hook so `run-hook` fires automatically.
 * The generated hook cd's into this CLI project and runs it via tsx.
 */
program
  .command('init')
  .description('Install the GitAgent pre-commit hook into this repository')
  .action(async () => {
    const git = new GitClient();

    if (!(await git.validateGitEnvironment())) {
      console.error('[gitagent] Not a git repository — run this inside a repo.');
      process.exitCode = 1;
      return;
    }

    const root = await git.getRepoRoot();
    const hooksDir = join(root, '.git', 'hooks');
    if (!existsSync(hooksDir)) {
      mkdirSync(hooksDir, { recursive: true });
    }

    // Absolute path to this CLI project, in a forward-slash form that the
    // POSIX sh that git uses to run hooks (Git Bash on Windows) understands.
    const projectDir = process.cwd().replace(/\\/g, '/');

    const hookPath = join(hooksDir, 'pre-commit');
    const hookScript =
      `#!/bin/sh\n` +
      `# Installed by GitAgent. Runs the run-hook command on every commit.\n` +
      `cd "${projectDir}" || exit 0\n` +
      `npx tsx src/index.ts run-hook\n`;

    writeFileSync(hookPath, hookScript, 'utf-8');
    // Make it executable (no-op on Windows filesystems, required on POSIX).
    try {
      chmodSync(hookPath, 0o755);
    } catch {
      /* chmod not supported on this filesystem — ignore */
    }

    console.log(`[gitagent] ✓ Installed pre-commit hook → ${hookPath}`);
    console.log('[gitagent] It will run automatically on your next `git commit`.');
  });

program.parseAsync(process.argv);
